file = open("Demo.txt","w")
l=["This is lagos \n","This is Python \n","This is Third Year class\n"]
file.write("Hello There \n")
file.writelines(l)
file.close()
file=open("Demo.txt",'r')
print("Output of the read functions")
print(file.read())
print()
file.seek(0)
print("Output of the readline functions")
print(file.readline())
print()
file.seek(0)
print("Output of read(12) function is")
print(file.read(12))
print()
file.seek(0)
print("Output of the readline function")
print(file.readline(8))
print()
file.seek(0)
print("Output of the readlines function")
print(file.readlines())
print()
file.close()
